export type Team="home"|"away";export type EventType="normal"|"foul"|"offside"|"goal"|"penalty";
export interface PlayerState{id:number;team:Team;x:number;z:number;vx:number;vz:number;role:string;number:number;stamina:number;decision:number}
export interface MatchEvent{id:number;type:EventType;clock:number;title:string;description:string;x:number;z:number;reviewable:boolean}
const HOME=[[-24,-42],[-8,-40],[8,-40],[24,-42],[-27,-18],[-9,-14],[9,-14],[27,-18],[-17,8],[17,8],[0,25],[0,0]];const AWAY=HOME.map(([x,z])=>[x,-z]);const ROLES=["GK","CB","CB","FB","FB","DM","CM","CM","W","W","ST","AM"];
export class MatchEngine{players:PlayerState[]=[];ball={x:0,z:0,vx:1.2,vz:3,owner:null as number|null};time=0;running=true;score={home:0,away:0};events:MatchEvent[]=[];private nextEvent=12;private nextId=1;private possession:Team="home";
constructor(){this.reset()}reset(){this.players=[];for(const[i,p]of HOME.entries())this.players.push(this.makePlayer(i,"home",p));for(const[i,p]of AWAY.entries())this.players.push(this.makePlayer(i+20,"away",p));this.ball={x:0,z:0,vx:1.2,vz:3,owner:null};this.time=0;this.running=true;this.score={home:0,away:0};this.events=[];this.nextEvent=12;this.possession="home"}
private makePlayer(id:number,team:Team,p:number[]){const i=id%20;return{id,team,x:p[0],z:p[1],vx:0,vz:0,role:ROLES[i]||"CM",number:i+1,stamina:1,decision:.7+Math.random()*.3}}
private dist(p:PlayerState,x:number,z:number){return Math.hypot(p.x-x,p.z-z)}private dir(t:Team){return t==="home"?1:-1}
step(dt:number){if(!this.running)return;this.time+=dt;this.updatePossession(dt);for(const p of this.players)this.updatePlayer(p,dt);if(this.ball.owner===null){this.ball.x+=this.ball.vx*dt;this.ball.z+=this.ball.vz*dt;this.ball.vx*=Math.pow(.97,dt*60);this.ball.vz*=Math.pow(.97,dt*60)}else{const o=this.players.find(p=>p.id===this.ball.owner);if(o){this.ball.x=o.x+o.vx*.08;this.ball.z=o.z+o.vz*.08;this.ball.vx=o.vx;this.ball.vz=o.vz}}this.checkBoundaries();this.checkBallInteractions();if(this.time>=this.nextEvent){this.tryCreateIncident();this.nextEvent=this.time+10+Math.random()*12}}
private updatePossession(dt:number){if(this.ball.owner!==null){const o=this.players.find(p=>p.id===this.ball.owner);if(!o)return;const enemy=this.players.filter(p=>p.team!==o.team).sort((a,b)=>this.dist(a,this.ball.x,this.ball.z)-this.dist(b,this.ball.x,this.ball.z))[0];if(enemy&&this.dist(enemy,this.ball.x,this.ball.z)<1.55&&Math.random()<dt*.7){this.ball.owner=enemy.id;this.possession=enemy.team}return}const nearest=this.players.slice().sort((a,b)=>this.dist(a,this.ball.x,this.ball.z)-this.dist(b,this.ball.x,this.ball.z))[0];if(nearest&&this.dist(nearest,this.ball.x,this.ball.z)<1.25){this.ball.owner=nearest.id;this.possession=nearest.team}}
private updatePlayer(p:PlayerState,dt:number){const dir=this.dir(p.team),attack=p.team===this.possession,bx=this.ball.x,bz=this.ball.z;let tx=p.x,tz=p.z;
// Only one outfield player is allowed to actively challenge the ball. Everyone else keeps shape.
const teammates=this.players.filter(q=>q.team===p.team);const nearest=teammates.filter(q=>q.role!=="GK").sort((a,b)=>this.dist(a,bx,bz)-this.dist(b,bx,bz))[0];const challenger=nearest?.id===p.id&&this.dist(p,bx,bz)<(p.role==="CM"||p.role==="DM"?8:6);
const ballRelX=Math.max(-1,Math.min(1,bx/34)),ballRelZ=Math.max(-1,Math.min(1,bz/52));
const baseX=p.role==="GK"?0:p.role==="CB"?(p.number===2?-8:8):p.role==="FB"?(p.number===4?-25:25):p.role==="DM"?-2:p.role==="CM"?(p.number%2?-10:10):p.role==="W"?(p.number%2?-20:20):p.role==="ST"?0:0;
let baseZ=p.role==="GK"?-dir*43:p.role==="CB"?-dir*30:p.role==="FB"?-dir*21:p.role==="DM"?-dir*9:p.role==="CM"?-dir*2:p.role==="W"?dir*10:p.role==="ST"?dir*23:dir*4;
// Compact team block shifts with the ball, but every role has a different response.
const shift=ballRelZ* (attack?9:6);tx=baseX+ballRelX*(p.role==="CB"?4:p.role==="FB"?7:p.role==="DM"?8:10);tz=baseZ+shift;
if(p.role==="GK")tz=dir>0?-43:43;
if(p.role==="CB"){tx+=ballRelX*(p.number===2?-3:3);if(Math.abs(bz)>25&&attack)tz+=dir*5}
if(p.role==="FB"){tx+=ballRelX*5;if(attack&&Math.abs(bx)>15)tz+=dir*7}
if(p.role==="DM"||p.role==="CM")tz+=attack?dir*2:-dir*2;
if(p.role==="W")tz+=attack?dir*9:0;
if(p.role==="ST")tz+=attack?dir*8:0;
if(challenger){tx=bx;tz=bz}
// Defenders never chase a ball into the opposite half unless they are the controlled challenger.
if((p.role==="CB"||p.role==="FB")&&!challenger)tz=Math.max(-46,Math.min(46,tz));
// Personal spacing prevents defenders and midfielders from stacking on top of each other.
for(const q of teammates){if(q.id===p.id)continue;const d=this.dist(p,q.x,q.z);if(d<4){const dx=p.x-q.x,dz=p.z-q.z,len=Math.hypot(dx,dz)||1;tx+=dx/len*(4-d)*1.8;tz+=dz/len*(4-d)*1.8}}
const noise=Math.sin(this.time*.37+p.id*7)*.55;tx+=noise;tz+=Math.cos(this.time*.31+p.id*3)*.35;tx=Math.max(-31,Math.min(31,tx));tz=Math.max(-49,Math.min(49,tz));const dx=tx-p.x,dz=tz-p.z,len=Math.hypot(dx,dz)||1;const speed=p.role==="GK"?3.1:p.role==="CB"?3.3:3.8;p.vx+=(dx/len*speed-p.vx)*Math.min(1,dt*3.5);p.vz+=(dz/len*speed-p.vz)*Math.min(1,dt*3.5);p.x+=p.vx*dt;p.z+=p.vz*dt;p.stamina=Math.max(.4,p.stamina-dt*.001*(Math.abs(p.vx)+Math.abs(p.vz)))}
private checkBallInteractions(){if(this.ball.owner!==null){const p=this.players.find(q=>q.id===this.ball.owner);if(!p)return;const opp=this.players.find(q=>q.team!==p.team&&this.dist(q,p.x,p.z)<2);if(opp&&Math.random()<.01){this.ball.owner=null;this.ball.vx=p.vx+(Math.random()-.5)*4;this.ball.vz=p.vz+(Math.random()-.5)*4;return}if(Math.random()<.004){const candidates=this.players.filter(q=>q.team===p.team&&q.id!==p.id&&Math.abs(q.z-p.z)<28);const target=candidates.sort((a,b)=>this.dist(a,p.x,p.z)-this.dist(b,p.x,p.z))[0];if(target){const dx=target.x-p.x,dz=target.z-p.z,len=Math.hypot(dx,dz)||1;this.ball.owner=null;this.ball.vx=dx/len*11;this.ball.vz=dz/len*11}}if(Math.random()<.0012&&Math.abs(p.z)>25){this.ball.owner=null;this.ball.vx=(Math.random()-.5)*6;this.ball.vz=this.dir(p.team)*(17+Math.random()*5)}}}
private checkBoundaries(){if(Math.abs(this.ball.x)>33){this.ball.x=Math.sign(this.ball.x)*32;this.ball.vx*=-.6}if(Math.abs(this.ball.z)>51){this.ball.z=Math.sign(this.ball.z)*49;this.ball.vz*=-.6}}
private tryCreateIncident(){const r=Math.random();if(r>.32)return;const x=this.ball.x,z=this.ball.z;const type:EventType=r<.12?"foul":r<.2?"offside":r<.25?"penalty":"goal";if(type==="goal"){const team=this.possession;this.score[team]++;this.events.unshift({id:this.nextId++,type,clock:this.time,title:"GOLO!",description:`Finalização concluída pelo ${team==="home"?"mandante":"visitante"}.`,x,z,reviewable:true});this.ball.owner=null;this.ball.x=0;this.ball.z=0;this.ball.vx=0;this.ball.vz=this.dir(team)*3;return}this.running=false;this.events.unshift({id:this.nextId++,type,clock:this.time,title:type==="foul"?"POSSÍVEL FALTA":type==="offside"?"POSSÍVEL IMPEDIMENTO":"POSSÍVEL PÊNALTI",description:"Lance gerado pela interação entre jogadores e bola. A arbitragem deve revisar a jogada.",x,z,reviewable:true})}
resume(){this.running=true}}
