export type Team="home"|"away";export type EventType="normal"|"foul"|"offside"|"goal"|"penalty";
export interface PlayerState{id:number;team:Team;x:number;z:number;vx:number;vz:number;role:string;number:number;stamina:number;decision:number}
export interface MatchEvent{id:number;type:EventType;clock:number;title:string;description:string;x:number;z:number;reviewable:boolean}
const HOME=[[-24,-42],[-8,-40],[8,-40],[24,-42],[-27,-18],[-9,-14],[9,-14],[27,-18],[-17,8],[17,8],[0,25],[0,0]];const AWAY=[[-24,42],[-8,40],[8,40],[24,42],[-27,18],[-9,14],[9,14],[27,18],[-17,-8],[17,-8],[0,-25],[0,0]];
const ROLES=["GK","CB","CB","FB","FB","DM","CM","CM","W","W","ST","AM"];
export class MatchEngine{players:PlayerState[]=[];ball={x:0,z:0,vx:2.4,vz:7,owner:null as number|null};time=0;running=true;score={home:0,away:0};events:MatchEvent[]=[];private nextEvent=12;private nextId=1;private possession:Team="home";
constructor(){this.reset()}
reset(){this.players=[];for(const [i,p] of HOME.entries())this.players.push(this.makePlayer(i,"home",p));for(const [i,p] of AWAY.entries())this.players.push(this.makePlayer(i+20,"away",p));this.ball={x:0,z:0,vx:1.2,vz:3,owner:null};this.time=0;this.running=true;this.score={home:0,away:0};this.events=[];this.nextEvent=12;this.possession="home"}
private makePlayer(id:number,team:Team,p:number[]){const i=id%20;return{id,team,x:p[0],z:p[1],vx:0,vz:0,role:ROLES[i]||"CM",number:i+1,stamina:1,decision:.7+Math.random()*.3}}
private dist(p:PlayerState,x:number,z:number){return Math.hypot(p.x-x,p.z-z)}
private homeDir(team:Team){return team==="home"?1:-1}
step(dt:number){if(!this.running)return;this.time+=dt;this.updatePossession(dt);for(const p of this.players)this.updatePlayer(p,dt);if(this.ball.owner===null){this.ball.x+=this.ball.vx*dt;this.ball.z+=this.ball.vz*dt;this.ball.vx*=Math.pow(.97,dt*60);this.ball.vz*=Math.pow(.97,dt*60)}else{const owner=this.players.find(p=>p.id===this.ball.owner);if(owner){this.ball.x=owner.x+owner.vx*.08;this.ball.z=owner.z+owner.vz*.08;this.ball.vx=owner.vx;this.ball.vz=owner.vz}}this.checkBoundaries();this.checkBallInteractions();if(this.time>=this.nextEvent){this.tryCreateIncident();this.nextEvent=this.time+10+Math.random()*12}}
private updatePossession(dt:number){const same=this.players.filter(p=>p.team===this.possession);const nearest=same.reduce((best,p)=>this.dist(p,this.ball.x,this.ball.z)<this.dist(best,this.ball.x,this.ball.z)?p:best,same[0]);if(this.ball.owner!==null){const owner=this.players.find(p=>p.id===this.ball.owner);if(!owner)return;const opponents=this.players.filter(p=>p.team!==owner.team);const opponent=opponents.reduce((best,p)=>this.dist(p,this.ball.x,this.ball.z)<this.dist(best,this.ball.x,this.ball.z)?p:best,opponents[0]);if(opponent&&this.dist(opponent,this.ball.x,this.ball.z)<1.7&&Math.random()<dt*.9){this.ball.owner=opponent.id;this.possession=opponent.team}}else if(nearest&&this.dist(nearest,this.ball.x,this.ball.z)<1.35){this.ball.owner=nearest.id;this.possession=nearest.team}}
private updatePlayer(p:PlayerState,dt:number){const dir=this.homeDir(p.team);let tx=p.x,tz=p.z;const bx=this.ball.x,bz=this.ball.z;const ballDist=this.dist(p,bx,bz);const teammates=this.players.filter(q=>q.team===p.team);const isClosest=teammates.every(q=>this.dist(q,bx,bz)>=ballDist-.05);const pressure=this.players.some(q=>q.team!==p.team&&this.dist(q,p.x,p.z)<6);const attack=p.team===this.possession;const zoneX=p.role==="FB"?(p.id%2?24:-24):p.role==="W"?(p.id%2?18:-18):0;let zoneZ=p.role==="GK"?-dir*43:p.role==="CB"?-dir*29:p.role==="FB"?-dir*22:p.role==="DM"?-dir*8:p.role==="ST"?dir*23:dir*6;
if(p.role==="GK"){tx=THREE_CLAMP(bx,-15,15);tz=dir>0?-43:43}else if(isClosest||ballDist<10){tx=bx;tz=bz}else{const attraction=attack?.35:.18;tx=zoneX+(bx-zoneX)*attraction;tz=zoneZ+(bz-zoneZ)*attraction;if(p.role==="FB"&&Math.abs(bx)>18)tz+=(attack?dir*8:dir*3);if(p.role==="ST")tx+=Math.sin(this.time*.73+p.id)*5;if(p.role==="CM"||p.role==="AM")tx+=Math.sin(this.time*.41+p.id)*4}if(!attack&&pressure&&p.role!=="GK")tz-=dir*3;const jitter=Math.sin(this.time*(.7+p.decision*.3)+p.id*13)*1.8;tx+=jitter*.35;tz+=Math.cos(this.time*.53+p.id)*1.2;const dx=tx-p.x,dz=tz-p.z,d=Math.hypot(dx,dz)||1;const speed=p.role==="GK"?3.4:p.role==="ST"?4.2:3.7;const desiredX=dx/d*speed,desiredZ=dz/d*speed;p.vx+=(desiredX-p.vx)*Math.min(1,dt*4.5);p.vz+=(desiredZ-p.vz)*Math.min(1,dt*4.5);p.x+=p.vx*dt;p.z+=p.vz*dt;p.x=THREE_CLAMP(p.x,-32,32);p.z=THREE_CLAMP(p.z,-50,50);p.stamina=Math.max(.35,p.stamina-dt*.001*(Math.abs(p.vx)+Math.abs(p.vz)))}
private checkBallInteractions(){if(this.ball.owner!==null){const p=this.players.find(q=>q.id===this.ball.owner);if(!p)return;const nearOpponent=this.players.find(q=>q.team!==p.team&&this.dist(q,p.x,p.z)<2.2);if(nearOpponent&&Math.random()<.015){this.ball.owner=null;this.ball.vx=p.vx+(Math.random()-.5)*5;this.ball.vz=p.vz+(Math.random()-.5)*5;return}if(Math.random()<.006){const teammates=this.players.filter(q=>q.team===p.team&&q.id!==p.id);const target=teammates.reduce((a,q)=>this.dist(q,p.x,p.z)<this.dist(a,p.x,p.z)?q:a,teammates[0]);if(target){const dx=target.x-p.x,dz=target.z-p.z,d=Math.hypot(dx,dz)||1;this.ball.owner=null;this.ball.vx=dx/d*12;this.ball.vz=dz/d*12}}if(Math.random()<.0015&&Math.abs(p.z)>25){this.ball.owner=null;this.ball.vx=(Math.random()-.5)*7;this.ball.vz=this.homeDir(p.team)*20}}}
private checkBoundaries(){if(Math.abs(this.ball.x)>33){this.ball.x=Math.sign(this.ball.x)*32;this.ball.vx*=-.6}if(Math.abs(this.ball.z)>51){this.ball.z=Math.sign(this.ball.z)*49;this.ball.vz*=-.6}}
private tryCreateIncident(){const r=Math.random();if(r>.32)return;const x=this.ball.x,z=this.ball.z;const type:EventType=r<.12?"foul":r<.2?"offside":r<.25?"penalty":"goal";if(type==="goal"){const team=this.ball.z>0?"away":"home";this.score[team]++;this.events.unshift({id:this.nextId++,type,clock:this.time,title:"GOLO!",description:`Finalização concluída pelo ${team==="home"?"mandante":"visitante"}.`,x,z,reviewable:true});this.ball.owner=null;this.ball.x=0;this.ball.z=0;this.ball.vx=0;this.ball.vz=this.homeDir(team)*3;return}this.running=false;this.events.unshift({id:this.nextId++,type,clock:this.time,title:type==="foul"?"POSSÍVEL FALTA":type==="offside"?"POSSÍVEL IMPEDIMENTO":"POSSÍVEL PÊNALTI",description:"Lance gerado pela interação entre jogadores e bola. A arbitragem deve revisar a jogada.",x,z,reviewable:true})}}
const THREE_CLAMP=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));